const TASK_FEATURES = {
  HAS_PASSWORD: 1,
  LOGIN_WITH_PASSWORD: 2,
  LOGIN_WITH_SMS_CODE: 4,
  HAS_PAYMENT_PASSWORD: 8
}

const TASK_TYPICAL_FEATURE_DEFINITIONS = {
  1: TASK_FEATURES.LOGIN_WITH_SMS_CODE,
  2: TASK_FEATURES.LOGIN_WITH_PASSWORD | TASK_FEATURES.HAS_PASSWORD |
    TASK_FEATURES.HAS_PAYMENT_PASSWORD
}

export default {
  TASK_FEATURES,
  TASK_TYPICAL_FEATURE_DEFINITIONS
}
